### PR TITLE
Rails 4.2 routes, fixes #152

### LINKED ISSUE #152: Route related error when starting server
Hey

I get the following error when starting my server
```
/Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:261:in `block (2 levels) in check_controller_and_action': '' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use (ArgumentError)
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:312:in `translate_controller'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:257:in `block in check_controller_and_action'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:272:in `check_part'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:256:in `check_controller_and_action'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:177:in `normalize_options!'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:99:in `initialize'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:77:in `new'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:77:in `build'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:1549:in `add_route'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:1526:in `decomposed_match'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:1507:in `block in match'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:1497:in `each'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/mapper.rb:1497:in `match'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/apotomo-1.3.0/config/routes.rb:2:in `block in <top (required)>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/route_set.rb:377:in `instance_exec'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/route_set.rb:377:in `eval_block'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/actionpack-4.2.0.beta2/lib/action_dispatch/routing/route_set.rb:355:in `draw'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/apotomo-1.3.0/config/routes.rb:1:in `<top (required)>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `load'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `block in load'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:233:in `load_dependency'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:242:in `load'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/initializable.rb:30:in `run'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/jokklan/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/application.rb:349:in `initialize!'
	from /Users/jokklan/Rails/widgit-cms/test/dummy/config/environment.rb:5:in `<top (required)>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `require'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `block in require'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:233:in `load_dependency'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/activesupport-4.2.0.beta2/lib/active_support/dependencies.rb:248:in `require'
	from /Users/jokklan/Rails/widgit-cms/test/dummy/config.ru:3:in `block in <main>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/builder.rb:55:in `initialize'
	from /Users/jokklan/Rails/widgit-cms/test/dummy/config.ru:in `new'
	from /Users/jokklan/Rails/widgit-cms/test/dummy/config.ru:in `<main>'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/builder.rb:49:in `eval'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/builder.rb:40:in `parse_file'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/server.rb:301:in `build_app_and_options_from_config'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/server.rb:208:in `app'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/server.rb:61:in `app'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/rack-1.6.0.beta/lib/rack/server.rb:339:in `wrapped_app'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/server.rb:78:in `start'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jokklan/.rvm/gems/ruby-2.1.1@widgit-cms/gems/railties-4.2.0.beta2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Do someone have any idea what could cause this error?

I use Rails 4.2.0.beta and are running my server from a dummy application inside a Rails engine, i don't know if that changes anything?

### PR DESCRIPTION
**Pull request by zoer**
Get working with rails 4.2 routes. Fix for #152.

### CODE REVIEW

**Comment by apotonick** [comment]
Do the tests still pass with Rails < 4.2?

**Comment by musaffa** [comment]
@apotonick This fix works with rails 4.1.10. Please fix this problem asap. :)

**Comment by apotonick** [comment]
Yeah but it also has to work with 3.x?! If you guys could sort that out I will merge it instantly!!

**Comment by musaffa** [comment]
You aren't confident about your tests. :p

**Pull request merged**
